language: "en-US"
early_access: true
reviews:
  profile: "senior"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
  request_changes_workflow: true
  high_level_summary: true
chat:
  auto_reply: true
